### ISSUE TITLE
Infinite animation

### ISSUE THREAD

**Issue by demkovych** [roginfarrer/react-collapsed#14] opened 2019-03-13 11:09 UTC
My collapsed block has top and bottom padding. When i collapsed it - block height increases indefinitely (in animation loop). Looks like it increases by collapsed block height + padding every second.

**Comment by roginfarrer** [comment] 2019-03-13 15:51
Can you provide a codesandbox example? Or some steps to reproduce? Which version?

**Comment by demkovych** [comment] 2019-03-14 09:01
@roginfarrer Can't, cause I received `TypeError: Cannot read property 'useMemo' of undefined` every time, when i tried to use your library in code sandbox

**Comment by roginfarrer** [comment] 2019-03-14 16:15
Sounds like you don't have React installed. The library requires React v16.8.x.

Here's a [codesandbox demo](https://codesandbox.io/s/kx0pn3nnv7)

**Comment by roginfarrer** [comment] 2019-03-25 20:05
Closing due to inactivity.

**Comment by Saranchenkov** [comment] 2019-06-19 13:31
The same bug!
We can easily reproduce it by adding padding to container that receives collapse props.
I tried it with basic demo on your demo site

![image](https://user-images.githubusercontent.com/25454843/59769881-ab287c00-92af-11e9-8f4b-edc7f37476dd.png)

**Comment by roginfarrer** [comment] 2019-06-23 17:12
I think this is related to challenges measuring the element with padding applied. Will need to dig in further.

**Comment by Sandstedt** [comment] 2019-08-20 14:52
A quick fix is to apply padding to the child element instead.
`<section {...getCollapseProps()}><div style={{ padding: 20 }}>{props.children}</div></section>`

**Comment by roginfarrer** [comment] 2019-09-27 02:40
I'm thinking the solution here is just to document this limitation and add a `console.warn` if the `padding` property is passed to the Collapse. I looked into getting the vertical padding when measuring the element's dimensions via `window.getComputedStyle`, but that operation is costly, and still doesn't give a smooth closing transition (the transition ends at the element's sum of the top and bottom padding, not `0`). As @Sandstedt said, the best solution here is to apply padding to the children instead.

**Closed** 2020-01-02 01:20 UTC
